version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6
     steps:
       - run: pip install -r requirements
       - run: flake8 hello_world.py directive_example.py
       - run: python test.py